/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"

/* Other patches */
#include "alttab.h"
#include "alwaysontop.h"
#include "attachx.h"
#include "recttoclient.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "floatpos.h"
#include "focusurgent.h"
#include "fullscreen.h"
#include "mpdcontrol.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "setborderpx.h"
#include "swallow.h"
#include "togglefullscreen.h"
#include "unfloatvisible.h"
#include "vanitygaps.h"
#include "xresources.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_fibonacci.h"
#include "layout_flextile-deluxe.h"
#include "layout_grid.h"
#include "layout_monocle.h"

