/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tags.c"

/* Other patches */
#include "alttab.c"
#include "alwaysontop.c"
#include "attachx.c"
#include "recttoclient.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "floatpos.c"
#include "focusurgent.c"
#include "fullscreen.c"
#include "mpdcontrol.c"
#include "moveresize.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "setborderpx.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "unfloatvisible.c"
#include "vanitygaps.c"
#include "xresources.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_fibonacci.c"
#include "layout_flextile-deluxe.c"
#include "layout_grid.c"
#include "layout_monocle.c"

